"""existing schema

Revision ID: 0001_existing_schema
Revises:
Create Date: 2026-07-11 16:16:41.897594
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = '0001_existing_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('paths_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('trust_level', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_trace_id'), 'tasks', ['trace_id'], unique=True)
    op.create_table('action_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dry_run_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_proposals_risk_level'), 'action_proposals', ['risk_level'], unique=False)
    op.create_index(op.f('ix_action_proposals_status'), 'action_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_action_proposals_task_id'), 'action_proposals', ['task_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_tool_name'), 'action_proposals', ['tool_name'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_prompt_hash'), 'ai_analyses', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_ai_analyses_status'), 'ai_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_ai_analyses_task_id'), 'ai_analyses', ['task_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_task_id'), 'approvals', ['task_id'], unique=False)
    op.create_table('config_baseline_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('current_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['config_baselines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_baseline_checks_baseline_id'), 'config_baseline_checks', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_config_baseline_checks_status'), 'config_baseline_checks', ['status'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'turn_index', name='uq_conversation_turn_index')
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_parent_task_id'), 'conversation_turns', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_task_id'), 'conversation_turns', ['task_id'], unique=True)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_vector_id'), 'knowledge_chunks', ['vector_id'], unique=False)
    op.create_table('safety_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('matched_rules_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_reviews_review_type'), 'safety_reviews', ['review_type'], unique=False)
    op.create_index(op.f('ix_safety_reviews_task_id'), 'safety_reviews', ['task_id'], unique=False)
    op.create_table('system_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_snapshots_task_id'), 'system_snapshots', ['task_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_stage'), 'task_events', ['stage'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_status'), 'tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_tool_calls_task_id'), 'tool_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_name'), 'tool_calls', ['tool_name'], unique=False)
    op.create_table('audit_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['task_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index(op.f('ix_audit_chain_event_id'), 'audit_chain', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_chain_trace_id'), 'audit_chain', ['trace_id'], unique=False)
    op.create_table('execution_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('tool_call_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('executor_mode', sa.String(length=64), nullable=False),
    sa.Column('runtime_user', sa.String(length=128), nullable=False),
    sa.Column('runtime_uid', sa.Integer(), nullable=False),
    sa.Column('target_user', sa.String(length=128), nullable=False),
    sa.Column('allowed', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['action_proposals.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_records_allowed'), 'execution_records', ['allowed'], unique=False)
    op.create_index(op.f('ix_execution_records_proposal_id'), 'execution_records', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_execution_records_task_id'), 'execution_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_execution_records_tool_call_id'), 'execution_records', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_execution_records_tool_name'), 'execution_records', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_records_tool_name'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_tool_call_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_task_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_proposal_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_allowed'), table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_index(op.f('ix_audit_chain_trace_id'), table_name='audit_chain')
    op.drop_index(op.f('ix_audit_chain_event_id'), table_name='audit_chain')
    op.drop_table('audit_chain')
    op.drop_index(op.f('ix_tool_calls_tool_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_task_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_status'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_stage'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_system_snapshots_task_id'), table_name='system_snapshots')
    op.drop_table('system_snapshots')
    op.drop_index(op.f('ix_safety_reviews_task_id'), table_name='safety_reviews')
    op.drop_index(op.f('ix_safety_reviews_review_type'), table_name='safety_reviews')
    op.drop_table('safety_reviews')
    op.drop_index(op.f('ix_knowledge_chunks_vector_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_conversation_turns_task_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_parent_task_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_config_baseline_checks_status'), table_name='config_baseline_checks')
    op.drop_index(op.f('ix_config_baseline_checks_baseline_id'), table_name='config_baseline_checks')
    op.drop_table('config_baseline_checks')
    op.drop_index(op.f('ix_approvals_task_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_ai_analyses_task_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_status'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_prompt_hash'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_action_proposals_tool_name'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_task_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_status'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_risk_level'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_index(op.f('ix_tasks_trace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('knowledge_documents')
    op.drop_table('conversations')
    op.drop_table('config_baselines')
    # ### end Alembic commands ###
