"""async task runtime

Revision ID: 0002_async_task_runtime
Revises: 0001_existing_schema
Create Date: 2026-07-11 16:17:45.402306
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_async_task_runtime'
down_revision: Union[str, Sequence[str], None] = '0001_existing_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_task_jobs_attempt_count_nonnegative'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_jobs_available_at'), 'task_jobs', ['available_at'], unique=False)
    op.create_index('ix_task_jobs_claim', 'task_jobs', ['status', 'available_at', 'id'], unique=False)
    op.create_index('ix_task_jobs_expired_lease', 'task_jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_task_jobs_status'), 'task_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_task_jobs_task_id'), 'task_jobs', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_jobs_task_id'), table_name='task_jobs')
    op.drop_index(op.f('ix_task_jobs_status'), table_name='task_jobs')
    op.drop_index('ix_task_jobs_expired_lease', table_name='task_jobs')
    op.drop_index('ix_task_jobs_claim', table_name='task_jobs')
    op.drop_index(op.f('ix_task_jobs_available_at'), table_name='task_jobs')
    op.drop_table('task_jobs')
    # ### end Alembic commands ###
